package server;

public enum Endpoint {
    GET_TASKS,
    GET_SUBTASKS,
    GET_EPICS,
    GET_ALL_TASKS,
    GET_TASK_BY_ID,
    GET_SUBTASK_BY_ID,
    GET_EPIC_BY_ID,
    POST_TASK,
    POST_SUBTASK,
    POST_EPIC,
    DELETE_TASK,
    DELETE_SUBTASK,
    DELETE_EPIC,
    DELETE_ALL_TASKS,
    DELETE_TASKS,
    DELETE_SUBTASKS,
    DELETE_EPICS,
    GET_EPIC_SUBTASKS,
    GET_HISTORY,
    UNKNOWN
}
